- name: check /etc/os-release
  become: false
  hosts:
  - servers

  #environment:
  #  http_proxy: http://proxy.example.com:8080
  #  https_proxy: http://proxy.example.com:8080

  pre_tasks:
  - name: load os-specific variables
    ansible.builtin.include_vars:
      file: "{{ item.file }}"
    when: ansible_facts['os_family'] == item.os_family
    loop:
      - { file: "redhat_vars.yml", os_family: "RedHat" }
      - { file: "debian_vars.yml", os_family: "Debian" }
      - { file: "freebsd_vars.yml", os_family: "FreeBSD" }
    tags: always

  tasks:
  - name: check /etc/os-release
    ansible.builtin.shell: |
      cat /etc/os-release
    register: res

#  - name: show os-release
#    ansible.builtin.debug:
#      msg: "{{ res.stdout_lines }}"
  
  - name: show os-release
    ansible.builtin.debug:
      var: res.stdout_lines

