- name: setup sssd-ldap
  hosts:
  #- ubuntu
  - localhost

  roles:
    - role: sssd
      tags: sssd
    
    - role: sudo
      tags: sudo

    - role: sway
      tags: sway, never
   
    - role: wayvnc
      tags: wayvnc, never 
