- name: setup freebsd
  hosts:
  - router10

  roles:
  - name: ntp
    tags: ntp

  - name: base
    tags: base

  - name: graphics
    tags: graphics

  - name: wayland
    tags: wayland

  - name: lightdm
    tags: lightdm

  - name: xfce
    tags: xfce

  - name: sssd
    tags: sssd

  - name: static_ip
    tags: static_ip

  - name: ipv6
    tags: ipv6

  - name: routing
    tags: routing

  - name: router
    tags: router

  - name: dhcpd
    tags: dhcpd

