---
bridges:
- name: wan
  type: bridge

- name: inet
  type: bridge

- name: opt1
  type: bridge

- name: opt2
  type: bridge

- name: opt3
  type: bridge

- name: opt4
  type: bridge

kvmusers:
- myuser

