---
- name: install sdk
  ansible.builtin.package:
    name:
    - alpine-sdk
    - linux-pam-dev
    state: present

- name: download aports
  ansible.builtin.shell: |
    cd /root/
    if [ ! -e "{{ aports_tar }}" ]; then
      curl -L -O {{ aports_url }}
    fi

- name: extract aports
  ansible.builtin.shell: |
    cd /root/
    tar xjvf {{ aports_tar }}

- name: remove doas
  ansible.builtin.shell: |
    apk del doas

- name: enable pam
  ansible.builtin.lineinfile:
    path: /root/aports-v{{ aports_ver }}/main/doas/APKBUILD
    regexp: '--without-pam'
    state: absent

- name: generate keys
  ansible.builtin.shell: |
    abuild-keygen -a -n

- name: abuild cleanpkg
  ansible.builtin.shell: |
    if [ -d "/root/packages/main/x86_64" ]; then
      cd /root/aports-v{{ aports_ver }}/main/doas
      abuild -r -F cleanpkg
    fi
  ignore_errors: true

- name: abuild deps
  ansible.builtin.shell: |
    cd /root/aports-v{{ aports_ver }}/main/doas
    abuild -r -F deps
    abuild -r -F fetch

- name: abuild fetch
  ansible.builtin.shell: |
    cd /root/aports-v{{ aports_ver }}/main/doas
    abuild -r -F fetch

- name: abuild unpack
  ansible.builtin.shell: |
    cd /root/aports-v{{ aports_ver }}/main/doas
    rm -rf ./pkg ./src
    abuild -r -F unpack

- name: abuild prepare
  ansible.builtin.shell: |
    cd /root/aports-v{{ aports_ver }}/main/doas
    abuild -r -F prepare

- name: abuild build
  ansible.builtin.shell: |
    cd /root/aports-v{{ aports_ver }}/main/doas
    abuild -r -F build
  register: res

- name: show build log
  debug: var=res

- name: abuild rootpkg
  ansible.builtin.shell: |
    cd /root/aports-v{{ aports_ver }}/main/doas
    abuild -r -F rootpkg

- name: install doas-pam
  ansible.builtin.shell: |
    apk add --allow-untrusted /root/packages/main/x86_64/doas-*.apk
    apk add doas-sudo-shim

- name: revise auth in /etc/pam.d/doas
  ansible.builtin.replace:
    path: /etc/pam.d/doas
    regexp: 'auth(\s+)include(\s+)system-auth'
    replace: 'auth\1include\2base-auth'

- name: revise account in /etc/pam.d/doas
  ansible.builtin.replace:
    path: /etc/pam.d/doas
    regexp: 'account(\s+)include(\s+)system-auth'
    replace: 'account\1include\2base-account'

- name: revise session in /etc/pam.d/doas
  ansible.builtin.replace:
    path: /etc/pam.d/doas
    regexp: 'session(\s+)include(\s+)system-auth'
    replace: 'session\1include\2base-session'

- name: allow ldapwheel group
  ansible.builtin.template:
    src: ldapwheel.conf
    dest: /etc/doas.d/

