---
- name: install kvm
  ansible.builtin.apt:
    name:
    - qemu-kvm
    - virt-manager
    state: present

- name: add users to libvirt group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: libvirt
    append: yes
  loop: "{{ kvmusers }}"

